### ISSUE TITLE
Sublime & git problem

### ISSUE THREAD

**Issue by dieka2501** [MokoVersity/mokoid-camp2-booklog#4]
Hello
1. I try to generate HTML with jade, but why the result like this (look the pic
   !
   ![jade](https://f.cloud.github.com/assets/319068/1166711/8ee498b4-2080-11e3-90aa-3a513d3e9898.png)

)
1. Following this instraction https://sublime.wbond.net/installation#st3, i get this message
   >>> import urllib.request,os; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); urllib.request.install_opener( urllib.request.build_opener( urllib.request.ProxyHandler()) ); open(os.path.join(ipp, pf), 'wb').write(urllib.request.urlopen( 'http://sublime.wbond.net/' + pf.replace(' ','%20')).read())
   Traceback (most recent call last):
   File "X/urllib/request.py", line 1252, in do_open
   File "X/http/client.py", line 1049, in request
   File "X/http/client.py", line 1087, in _send_request
   File "X/http/client.py", line 1045, in endheaders
   File "X/http/client.py", line 890, in _send_output
   File "X/http/client.py", line 828, in send
   File "X/http/client.py", line 806, in connect
   File "X/socket.py", line 424, in create_connection
   File "X/socket.py", line 415, in create_connection
   TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "X/urllib/request.py", line 160, in urlopen
  File "X/urllib/request.py", line 473, in open
  File "X/urllib/request.py", line 491, in _open
  File "X/urllib/request.py", line 451, in _call_chain
  File "X/urllib/request.py", line 1272, in http_open
  File "X/urllib/request.py", line 1255, in do_open
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 680, in update_compressed_packages
    multi_importer.loaders = [ZipLoader(p) for p in pkgs]
  File "/opt/sublime_text/sublime_plugin.py", line 680, in <listcomp>
    multi_importer.loaders = [ZipLoader(p) for p in pkgs]
  File "/opt/sublime_text/sublime_plugin.py", line 588, in __init__
    z = zipfile.ZipFile(zippath, 'r')
  File "X/zipfile.py", line 910, in **init**
  File "X/zipfile.py", line 944, in _GetContents
  File "X/zipfile.py", line 959, in _RealGetContents
zipfile.BadZipFile: File is not a zip file

and i can't find installation package, and emme, why?
1. when i try push to git ($ git push origin master) i get this message "Warning: Permanently added the RSA host key for IP address '192.30.252.130' to the list of known hosts.
   Permission denied (publickey).
   fatal: The remote end hung up unexpectedly" and the file not uploaded into my repo, why? 

PS : my internet connection is good enough

Thanks

**Comment by jollen** [comment]
Your generated HTML is minified. Please add parameter '-P' to your Jade command line, which will generate a development (not minified) copy.

**Comment by dieka2501** [comment]
ahh.. ok.. done.. thank :")
